


###
POST {{base_url}}/api/user/register
Origin: http://localhost:4000
Content-Type: application/json
version: 1.2.4

{
  "name": "test",
  "email": "test@gmail.com",
  "password": "3243243232"
}



###
POST {{base_url}}/api/user/login
Origin: http://localhost:4000
Content-Type: application/json
version: 1.2.4

{
  "email": "test@gmail.com",
  "password": "3243243232"
}